# Generated by Django 4.2.6 on 2023-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgroups',
            options={'verbose_name': 'Item group', 'verbose_name_plural': 'Item groups'},
        ),
        migrations.AlterModelOptions(
            name='placeitems',
            options={'verbose_name': 'Place item', 'verbose_name_plural': 'Place items'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booked_tables',
            new_name='people_number',
        ),
    ]
