# Generated by Django 4.2.6 on 2023-10-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_itemgroups_options_alter_placeitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='places.place'),
        ),
    ]
