# Generated by Django 4.2.6 on 2023-11-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_booking_time_booking_booking_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroups',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
